language: python
python:
  - 3.7.4

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="gearwheel.settings.travis"

services:
  - postgresql

script:
  - ./manage.py pytest
